### ISSUE TITLE
Curious on release of models and datasets?

### ISSUE THREAD

**Issue by imr555** [Hon-Wong/Elysium#1]
Thanks to the authors on such a nice task on Video Grounding on Objects.

We were curious on the release of datasets and models from this paper.

Is there any plan to release them?

Thanks in Advance and Best Regards,

**Comment by Hon-Wong** [comment]
Thank you for your attention! We are currently in the process of refactoring the code and formatting the dataset. We expect that the codes and datasets will be released within the next few weeks.

**Comment by Hon-Wong** [comment]
Codes and datasets have been released.
