### ISSUE TITLE
evaluation split

### ISSUE THREAD

**Issue by miranheo** [Hon-Wong/Elysium#11]
could you share the evaluation split used for the VideoREG task?

**Comment by Hon-Wong** [comment]
see [here](https://huggingface.co/datasets/Hon-Wong/ElysiumTrack-val500)

**Comment by miranheo** [comment]
Thanks! Where can I get the frames? I tried downloading the videos from the URL and extracting the frames at 1 fps, but they are not aligned with the annotation.

**Comment by Hon-Wong** [comment]
You can find the frames [here](https://huggingface.co/datasets/Hon-Wong/ElysiumTrack-val500/resolve/main/frames.zip?download=true). 

Feel free to reach out to me if you have any further questions.

**Comment by miranheo** [comment]
Thank you so much :)
