### ISSUE TITLE
Raw Results of LaSOT and UAV123

### ISSUE THREAD

**Issue by yangchris11** [Hon-Wong/Elysium#13]
Thank you for the awesome work and dataset! 

I was wondering if you can also provide the zero-shot raw (tracking) results of LaSOT and UAV123?

Thank you very much!

**Comment by Hon-Wong** [comment]
Sure, I'll share the raw results in 1 or 2 days.

BW,
Han

**Comment by yangchris11** [comment]
Thank you very much! I'll take a look into that!

Closing the issue :+1:

**Comment by yangchris11** [comment]
FYI, I found there are a couple missing bracklets in the json result files

<img width="835" alt="Screenshot 2024-10-24 at 14 53 53" src="https://github.com/user-attachments/assets/357fc7c6-def3-4257-a2ff-ebc5ec905a84">

<img width="79" alt="Screenshot 2024-10-24 at 14 55 56" src="https://github.com/user-attachments/assets/452201a7-7824-442a-b52f-9988293f426b">

**Comment by Hon-Wong** [comment]
Yes, the output of MLLM collapses occasionally. For a strict evaluation, we simply pad with [0,0,0,0] for these cases. I guess trying a different prompt might solve the problem.
