### ISSUE TITLE
Processed tracking datasets in JSON format.

### ISSUE THREAD

**Issue by Xuchen-Li** [Hon-Wong/Elysium#4]
Hello, thank you for your wonderful work.
Could you share the processed tracking datasets in JSON format?
It would be greatly convenient.

**Comment by Hon-Wong** [comment]
Please check https://huggingface.co/datasets/sty-yyj/ElysiumTrack-1M/blob/main/ElysiumTrack-1M.json

**Comment by Xuchen-Li** [comment]
oh, thanks a lot!
