### ISSUE TITLE
question about: load pretrained model for evaluation  

### ISSUE THREAD

**Issue by lixit** [Hon-Wong/Elysium#7]
when I use this line to load the pre-trained model:
`AutoModelForCausalLM.from_pretrained("sty-yyj/elysium_7b", trust_remote_code=True)`

This error occurs
```
Exception has occurred: ValueError
The model class you are passing has a `config_class` attribute that is not consistent with the config class you passed (model has None and you passed <class 'transformers_modules.sty-yyj.elysium_7b.f804b8c94a991b33ae30c643332c489d6ae93abe.modeling_elysium.ElysiumConfig'>. Fix one of those so they match!
```

Could you explain what's wrong with this method?

**Comment by Hon-Wong** [comment]
The configuration we use is available at Elysium/models/modeling_elysium.py. Therefore, I suggest running this line after cd Elysium's root folder to make sure the dependency is correctly imported. If this does not work, you can try downloading sty-yyj/elysium_7b to a local path (YOUR_LOCAL_PATH) and then set up the model with: AutoModelForCausalLM.from_pretrained("YOUR_LOCAL_PATH", trust_remote_code=True)

**Comment by lixit** [comment]
After cd to Elysium's root folder, this still doesn't work.

But I am able to load the model after download it to a local path.

Also I noticed by using this:
`AutoModelForCausalLM.from_pretrained("local/path/to/elysium_7b", trust_remote_code=True)`

The code inside `local/path/to/elysium_7b/modeling_elysium.py` will be run instead of the code cloned from Github.

This is not what I wanted. I want the code in the main github repository `Elysium/models/modeling_elysium.py` to be run. 

Is this related to [https://huggingface.co/docs/transformers/en/custom_models#sending-the-code-to-the-hub](url) ?

Since it says This API is experimental.

And how do you suggest to run the code in the main Github repository?

**Comment by Hon-Wong** [comment]
To maintain the simplicity of the Elysium codebase, we directly utilize AutoModelForCausalLM for model loading in eval.py. This approach ensures that the code within elysium_7b is executed. However, if you seek to alter the architecture of Elysium, you can make references to train.py, where we have provided flexibility for modifications.
