### ISSUE TITLE
Regarding the VRAM usage of each GPU

### ISSUE THREAD

**Issue by zhaosonghui** [Hon-Wong/Elysium#9]
This is a very valuable study! During the training process, how much VRAM does each A800 GPU approximately use? I would like to know if it is feasible to replicate the experiment using a 4090 (24GB) version of the GPU

**Comment by Hon-Wong** [comment]
We use A100-80G for training. You may need some tricks to run the experiment on 4090, e.g., lora, 8-bit, etc.
